authors:
  gabrielbdornas:
    name: Gabriel Braico Dornas
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/49699290
  andrelamor:
    name: André Luiz Guimarães Amorim
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/52294411?v=4

