authors:
  gabrielbdornas:
    name: Gabriel Braico Dornas
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/49699290
  andrelamor:
    name: André Luiz Guimarães Amorim
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/52294411?v=4
  lucasfainblat:
    name: Lucas Fainblat
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/153224852?v=4
  augustacora:
    name: Augusta Cora
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/146127524?v=4
  Isabelle-Fernandes:
    name: Isabelle Fernandes de Oliveira
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/65547646?v=4
  raianecardoso:
    name: Raiane Cardoso
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/166438302?v=4
  henriquesiqr:
    name: Henrique Siqueira
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/170460655?v=4
  felpsop:
    name: Felipe Oliveira
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/166438097?v=4
  LeyTeodoro:
    name: Leyverson Teodoro
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/159444286?v=4
  diegovianasilva:
    name: Diego Viana Silva
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/188073225?v=4
  JoaoVitorFonsseca:
    name: João Vitor Fonseca
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/188368099?v=4
  leidisalves:
    name: Leidi Alves
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/188377903?v=4
  caizin07:
    name: Caio Silva Moreira
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/97908080?v=4
  mateusribeiro12:
    name: Mateus Ribeiro
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/191279792?v=4
