# This uses a reusable workflow
name: Add assignee to closed issue

on:
  issues:
    types: [closed]

jobs:
  add_assignee_to_closed_issue:
    uses: meadapt/github-actions-reutilizaveis/.github/workflows/add_assignee_to_closed_issue_reusable.yml@v2.5
    secrets:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
